spring.application.name=GameStore-1
server.servlet.context-path=/
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB	
# ÄÆ°á»ng dáº«n chá»©a file template (Máº·c Äá»nh lÃ  templates)
spring.thymeleaf.prefix=classpath:/templates/

# ÄuÃ´i file (Máº·c Äá»nh lÃ  .html)
spring.thymeleaf.suffix=.html

# Táº¯t cache Äá» khi sá»­a HTML chá» cáº§n F5 trÃ¬nh duyá»t lÃ  tháº¥y thay Äá»i (Ráº¥t cáº§n khi Äang code)
spring.thymeleaf.cache=false

# Ãp kiá»u mÃ£ hÃ³a lÃ  UTF-8 Äá» khÃ´ng bá» lá»i font tiáº¿ng Viá»t
spring.thymeleaf.encoding=UTF-8

# Káº¿t ná»i SQL Database
 spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GameStore;encrypt=true;trustServerCertificate=true
 spring.datasource.username=sa
 spring.datasource.password=PanzerTank4so9
 spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# giữ nguyên tên cột trong database
# Cáº¥u hÃ¬nh JPA

# ddl-auto: 
# update (cáº­p nháº­t schema), create (xÃ³a Äi táº¡o láº¡i má»i láº§n cháº¡y), 
# create-drop (xÃ³a khi táº¯t app), none (khÃ´ng lÃ m gÃ¬)
# spring.jpa.hibernate.ddl-auto=update

# Hiá»n thá» cÃ¢u lá»nh SQL ra console Äá» debug
# spring.jpa.show-sql=true

# Äá»nh dáº¡ng cÃ¢u lá»nh SQL cho dá» Äá»c
# spring.jpa.properties.hibernate.format_sql=true

# Cáº¥u hÃ¬nh trong application.properties Äá» hiá»n thá» endpoint beans
management.endpoints.web.exposure.include=beans
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trieule.727050@gmail.com
spring.mail.password=ffab whsa sppi zhgc


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true